### ISSUE TITLE
Include message in status response

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/discovery-service-backend#14]
Include a message in the status response from https://discovery.clarin.eu/status.

"ok" if successfull, description of the error otherwise.

**Comment by WillemElbers** [comment]
Fixed in release 1.9.2

**Comment by dietervu** [comment]
The message also seems to show error=true in case the metadata age is exactly 0 minutes, below one of the strings that statuscake received:

`{"countries":[{"name":"EU","count":1},{"name":"AT","count":41},{"name":"SI","count":12},{"name":"BE","count":37},{"name":"DE","count":228},{"name":"IT","count":73},{"name":"NL","count":31},{"name":"PL","count":11},{"name":"LV","count":17},{"name":"DK","count":60},{"name":"GB","count":544},{"name":"MY","count":1},{"name":"CN","count":1},{"name":"CA","count":1},{"name":"IE","count":1},{"name":"SE","count":48},{"name":"US","count":1},{"name":"EE","count":3},{"name":"CZ","count":89},{"name":"FI","count":46},{"name":"NO","count":1}],"lastModified":{"msSinceEpoch":1482103821000,"iso8601":"2016-12-18T23:30Z"},"unkown":1,"status":{"error":true,"message":"Metadata too old. Age=0 minutes, expected < 15 minutes."}} `

**Comment by WillemElbers** [comment]
I don't think this has happend for a long time and looking at the code (https://github.com/clarin-eric/discovery-service-backend/blob/develop/discovery-metadata-api/src/main/java/nl/mpi/shibboleth/ds/status/ServletStatus.java#L54) this does not seem to be possible to happen anymore. Please re-open if it does...
